package io.openfuture.chain.core.exception

class ChainOutOfSyncException : RuntimeException()